"""empty message

Revision ID: 24084f8aa9cb
Revises: 2e92841da7a6
Create Date: 2024-06-09 13:26:21.545264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24084f8aa9cb'
down_revision = '2e92841da7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_p', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id_p'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet_favorites')
    # ### end Alembic commands ###
